name: stdlinux test compile

on:
  push:
    branches:
      - main 
    paths:
      - 'src/*'
  workflow_dispatch:


jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Build binaries
        run: zig build -Dversion=1

      - name: Upload binaries
        uses: actions/upload-artifact@v3
        with:
          name: compiled-binaries
          path: zig-out/bin/

  test:
    needs: build
    runs-on: ubuntu-latest
    container: ghcr.io/mbund/stdlinux-compat:2024-09-01

    steps:
      - uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: compiled-binaries
          path: zig-out/bin/

      - name: Set execute permissions
        run: chmod +x zig-out/bin/*

      - name: Run all binaries
        run: |
          for binary in zig-out/bin/*; do
            echo "Running $binary"
            $binary --version || echo "Error running $binary" >&2
          done