name: Scheduled Release

on:
  schedule:
    - cron: '37 17 14 1 *'
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        type: string


jobs:
  create-tag:
    name: Create the Git tag
    if: >-
      github.event_name == 'workflow_dispatch' ||
      github.event.pull_request.merged == true
      && contains(github.event.pull_request.labels.*.name, 'release-version')
    runs-on: ubuntu-latest
    outputs:
      release-tag: ${{ steps.get-version.outputs.version }}
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Extract version to be released
        id: get-version
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "version=${{ github.event.inputs.version }}" >> "$GITHUB_OUTPUT"
          else
            TITLE="${{ github.event.pull_request.title }}"
            echo "version=${TITLE/: [[:alnum:]]*}" >> "$GITHUB_OUTPUT"
          fi
      - name: Bump version and push tag
        uses: mathieudutour/github-tag-action@v6.2
        with:
          custom_tag: "${{ steps.get-version.outputs.version }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tag_prefix: ""


  create-release:
    name: Create a release on GitHub's UI
    needs: create-tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Create release
        uses: softprops/action-gh-release@v2
        with:
          generate_release_notes: true
          tag_name: "${{ needs.create-tag.outputs.release-tag }}"

  upload-bins:
    runs-on: ubuntu-latest
    needs: [create-release, create-tag]
    permissions:
      contents: write
    steps:
      - name: Checkout ${{ needs.create-tag.outputs.release-tag }}
        uses: actions/checkout@v4
        with:
          ref: "${{ needs.create-tag.outputs.release-tag }}"

      - uses: mlugg/setup-zig@v1
        with:
          version: master

      - name: Build binaries
        run: |
          zig build -Doptimize=ReleaseSafe

      - name: Package source
        run: |
          git archive --format=tar.gz -o source.tar.gz HEAD

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            zig-out/bin/*
            source.tar.gz
          tag_name: "${{ needs.create-tag.outputs.release-tag }}"