name: stdlinux test compile

on:
  push:
    branches:
      - main 
    paths:
      - 'src/*'


jobs:
  test-compile:
    runs-on: ubuntu-latest
    container: ghcr.io/mbund/stdlinux-compat:2024-09-01

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Compile the code
        run: |
          make